public enum EventTargetObjectType
{
	Parent = 0,
	Self = 1,
	GameObject = 2,
	GameManager = 3,
	MainCamera = 4,
	PointCamera = 5,
	CollisionObject = 6,
	Player = 7,
	HeeMin = 8,
	SungA = 9,
	JiHyeon = 10,
	SoYoung = 11,
	BonGu = 12,
	DalSu = 13,
	CinemaAssets = 14,
	WomanHead = 15,
	MinJi = 16,
	Max = 17,
}
