Shader "CameraFilterPack/Special_Bubble" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 11927
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   float _TimeX;
					//   float _Value;
					//   float _Value2;
					//   float _Value3;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _TimeX       c0       1
					//   _Value       c1       1
					//   _Value2      c2       1
					//   _Value3      c3       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c4, 2, -1, 0.5, 0.150000006
					    def c5, 6.28318548, -3.14159274, 0.800000012, 0.200000003
					    def c6, 0.170000002, 0.400000006, 0.140000001, 0.600000024
					    def c7, 0.859436691, 0.286478877, 0.5, 0.03125
					    def c8, 1.4323945, 0.477464825, 0.90718317, 0.30239439
					    def c9, 0.286478907, 0.0954929665, 0.620704234, 0.206901416
					    dcl_texcoord_pp v0.xy
					    dcl_2d s0
					    mov r0.xz, c4
					    mov r1.x, c0.x
					    mad r2, r1.x, c8, r0.z
					    frc r2, r2
					    mad r2, r2, c5.x, c5.y
					    sincos r3.xy, r2.w
					    mad r0.yw, v0.xxzy, c4.x, c4.y
					    mad r0.w, r0.w, r0.x, -c2.x
					    mad r0.x, r0.y, r0.x, -c1.x
					    mad r0.y, r3.x, c5.z, r0.w
					    mul r0.y, r0.y, r0.y
					    sincos r4.y, r2.z
					    mad r1.y, r4.y, c5.w, r0.x
					    mad r0.y, r1.y, r1.y, r0.y
					    rsq r0.y, r0.y
					    mul r0.y, r3.y, r0.y
					    sincos r3.y, r2.x
					    sincos r4.xy, r2.y
					    mad r1.y, r3.y, c4.w, r0.x
					    mad r1.z, r4.x, c5.z, r0.w
					    mul r1.z, r1.z, r1.z
					    mad r1.y, r1.y, r1.y, r1.z
					    rsq r1.y, r1.y
					    mad r0.y, r1.y, r4.y, r0.y
					    mad r2, r1.x, c9, r0.z
					    frc r2, r2
					    mad r2, r2, c5.x, c5.y
					    sincos r3.y, r2.x
					    mad r0.z, r3.y, c6.x, r0.x
					    sincos r3.xy, r2.y
					    mad r1.y, r3.x, c6.y, r0.w
					    mul r1.y, r1.y, r1.y
					    mad r0.z, r0.z, r0.z, r1.y
					    rsq r0.z, r0.z
					    mad r0.y, r0.z, r3.y, r0.y
					    sincos r3.y, r2.z
					    sincos r4.xy, r2.w
					    mad r0.z, r3.y, c6.z, r0.x
					    mad r1.y, r4.x, c6.w, r0.w
					    mul r1.y, r1.y, r1.y
					    mad r0.z, r0.z, r0.z, r1.y
					    rsq r0.z, r0.z
					    mad r0.y, r0.z, r4.y, r0.y
					    mad r1.xy, r1.x, c7, c7.z
					    frc r1.xy, r1
					    mad r1.xy, r1, c5.x, c5.y
					    sincos r2.xy, r1.y
					    sincos r3.y, r1.x
					    mad r0.x, r3.y, c6.z, r0.x
					    mad r0.z, r2.x, c4.z, r0.w
					    mul r0.z, r0.z, r0.z
					    mad r0.x, r0.x, r0.x, r0.z
					    rsq r0.x, r0.x
					    mad r0.x, r0.x, r2.y, r0.y
					    mul r0.x, r0.x, c3.x
					    mul r0.x, r0.x, c7.w
					    mad r0.xy, v0, c5.z, -r0.x
					    texld oC0, r0, s0
					
					// approximately 128 instruction slots used (1 texture, 127 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _TimeX;
						float _Value;
						float _Value2;
						float _Value3;
						vec4 unused_0_5;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec2 u_xlat1;
					vec4 u_xlat2;
					vec2 u_xlat3;
					vec2 u_xlat7;
					float u_xlat9;
					void main()
					{
					    u_xlat0 = vec4(_TimeX) * vec4(9.0, 3.0, 5.69999981, 1.89999998);
					    u_xlat1.xy = cos(u_xlat0.yw);
					    u_xlat0 = sin(u_xlat0);
					    u_xlat7.xy = vs_TEXCOORD0.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
					    u_xlat7.xy = u_xlat7.xy * vec2(2.0, 2.0) + (-vec2(_Value, _Value2));
					    u_xlat1.xy = u_xlat1.xy * vec2(0.800000012, 0.800000012) + u_xlat7.yy;
					    u_xlat1.xy = u_xlat1.xy * u_xlat1.xy;
					    u_xlat0.xz = u_xlat0.xz * vec2(0.150000006, 0.200000003) + u_xlat7.xx;
					    u_xlat0.xz = u_xlat0.xz * u_xlat0.xz + u_xlat1.xy;
					    u_xlat0.xz = sqrt(u_xlat0.xz);
					    u_xlat0.xz = vec2(1.0, 1.0) / u_xlat0.xz;
					    u_xlat0.xy = u_xlat0.yw * u_xlat0.xz;
					    u_xlat0.x = u_xlat0.y + u_xlat0.x;
					    u_xlat2 = vec4(_TimeX) * vec4(1.80000007, 0.600000024, 3.89999986, 1.29999995);
					    u_xlat3.xy = cos(u_xlat2.yw);
					    u_xlat2 = sin(u_xlat2);
					    u_xlat3.xy = u_xlat3.xy * vec2(0.400000006, 0.600000024) + u_xlat7.yy;
					    u_xlat3.xy = u_xlat3.xy * u_xlat3.xy;
					    u_xlat1.xy = u_xlat2.xz * vec2(0.170000002, 0.140000001) + u_xlat7.xx;
					    u_xlat3.xy = u_xlat1.xy * u_xlat1.xy + u_xlat3.xy;
					    u_xlat3.xy = sqrt(u_xlat3.xy);
					    u_xlat3.xy = vec2(1.0, 1.0) / u_xlat3.xy;
					    u_xlat0.x = u_xlat3.x * u_xlat2.y + u_xlat0.x;
					    u_xlat0.x = u_xlat3.y * u_xlat2.w + u_xlat0.x;
					    u_xlat3.xy = vec2(_TimeX) * vec2(5.39999962, 1.79999995);
					    u_xlat9 = cos(u_xlat3.y);
					    u_xlat3.xy = sin(u_xlat3.xy);
					    u_xlat9 = u_xlat9 * 0.5 + u_xlat7.y;
					    u_xlat3.x = u_xlat3.x * 0.140000001 + u_xlat7.x;
					    u_xlat9 = u_xlat9 * u_xlat9;
					    u_xlat3.x = u_xlat3.x * u_xlat3.x + u_xlat9;
					    u_xlat3.x = sqrt(u_xlat3.x);
					    u_xlat3.x = float(1.0) / u_xlat3.x;
					    u_xlat0.x = u_xlat3.x * u_xlat3.y + u_xlat0.x;
					    u_xlat0.x = u_xlat0.x * _Value3;
					    u_xlat0.x = u_xlat0.x * 0.03125;
					    u_xlat0.xy = vs_TEXCOORD0.xy * vec2(0.800000012, 0.800000012) + (-u_xlat0.xx);
					    SV_Target0 = texture(_MainTex, u_xlat0.xy);
					    return;
					}"
				}
			}
		}
	}
}