Shader "CameraFilterPack/Blur_DitherOffset" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_Distortion ("_Distortion", Range(0, 1)) = 0.3
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
		_Level ("_Level", Range(1, 16)) = 4
		_Distance ("_Distance", Vector) = (30,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 33601
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Distance;
					//   float _Level;
					//   sampler2D _MainTex;
					//   float4 _ScreenResolution;
					//   float _TimeX;
					//
					//
					// Registers:
					//
					//   Name              Reg   Size
					//   ----------------- ----- ----
					//   _TimeX            c0       1
					//   _ScreenResolution c1       1
					//   _Level            c2       1
					//   _Distance         c3       1
					//   _MainTex          s0       1
					//
					
					    ps_3_0
					    def c4, 12.9898005, 78.2330017, 0, 43758.5469
					    def c5, 0.159154937, 0.5, 6.28318548, -3.14159274
					    def c6, 0, 1, -1, 0.5
					    defi i0, 255, 0, 0, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    frc r0.x, c0.x
					    add r0.xy, r0.x, v0
					    dp2add r0.x, r0, c4, c4.z
					    mad r0.x, r0.x, c5.x, c5.y
					    frc r0.x, r0.x
					    mad r0.x, r0.x, c5.z, c5.w
					    sincos r1.y, r0.x
					    mul r0.x, r1.y, c4.w
					    frc r0.x, r0.x
					    frc r0.y, c2.x
					    add r0.z, -r0.y, c2.x
					    cmp r0.y, -r0.y, c6.x, c6.y
					    mov r1.z, c4.z
					    cmp r0.y, c2.x, r1.z, r0.y
					    add r0.y, r0.y, r0.z
					    rcp r1.x, c1.x
					    rcp r1.y, c1.y
					    mul r0.zw, r1.xyxy, c3.xyxy
					    mad r1.xy, r0.zwzw, -c5.y, v0
					    mad r0.zw, r0, c5.y, v0.xyxy
					    add r0.zw, -r1.xyxy, r0
					    add r1.z, r0.y, c6.z
					    rcp r1.z, r1.z
					    mul r2.xy, r0.zwzw, r1.z
					    add r0.x, -r0.x, c5.y
					    cmp r0.x, r0.x, c6.w, c6.x
					    mad r2.xy, r0.x, r2, r1
					    mov r2.zw, c4.z
					    texldl r3, r2, s0
					    mov r4.zw, c4.z
					    mov r5, r3
					    mov r4.xy, r2
					    mov r0.x, c6.y
					    rep i0
					      mov r1.x, r0.y
					      break_ge r0.x, r1.x
					      mad r4.xy, r0.zwzw, r1.z, r4
					      texldl r6, r4, s0
					      add r5, r5, r6
					      add r0.x, r0.x, c6.y
					    endrep
					    rcp r0.x, r0.y
					    mul oC0, r0.x, r5
					
					// approximately 58 instruction slots used (4 texture, 54 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _TimeX;
						vec4 _ScreenResolution;
						float _Level;
						vec4 _Distance;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					bool u_xlatb0;
					vec2 u_xlat1;
					vec4 u_xlat2;
					vec4 u_xlat3;
					int u_xlati4;
					vec4 u_xlat5;
					int u_xlati6;
					bool u_xlatb10;
					float u_xlat12;
					vec2 u_xlat13;
					float u_xlat18;
					void main()
					{
					    u_xlat0.x = fract(_TimeX);
					    u_xlat0.xy = u_xlat0.xx + vs_TEXCOORD0.xy;
					    u_xlat0.x = dot(u_xlat0.xy, vec2(12.9898005, 78.2330017));
					    u_xlat0.x = sin(u_xlat0.x);
					    u_xlat0.x = u_xlat0.x * 43758.5469;
					    u_xlat0.x = fract(u_xlat0.x);
					    u_xlati6 = int(_Level);
					    u_xlat12 = trunc(_Level);
					    u_xlat1.xy = _Distance.xy / _ScreenResolution.xy;
					    u_xlat13.xy = (-u_xlat1.xy) * vec2(0.5, 0.5) + vs_TEXCOORD0.xy;
					    u_xlat1.xy = u_xlat1.xy * vec2(0.5, 0.5) + vs_TEXCOORD0.xy;
					    u_xlat1.xy = (-u_xlat13.xy) + u_xlat1.xy;
					    u_xlat18 = u_xlat12 + -1.0;
					    u_xlat1.xy = u_xlat1.xy / vec2(u_xlat18);
					    u_xlatb0 = 0.5>=u_xlat0.x;
					    u_xlat0.x = u_xlatb0 ? 0.5 : float(0.0);
					    u_xlat0.xw = u_xlat0.xx * u_xlat1.xy + u_xlat13.xy;
					    u_xlat2 = textureLod(_MainTex, u_xlat0.xw, 0.0);
					    u_xlat3 = u_xlat2;
					    u_xlat13.xy = u_xlat0.xw;
					    for(int u_xlati_loop_1 = 1 ; u_xlati_loop_1<u_xlati6 ; u_xlati_loop_1++)
					    {
					        u_xlat13.xy = u_xlat1.xy + u_xlat13.xy;
					        u_xlat5 = textureLod(_MainTex, u_xlat13.xy, 0.0);
					        u_xlat3 = u_xlat3 + u_xlat5;
					    }
					    SV_Target0 = u_xlat3 / vec4(u_xlat12);
					    return;
					}"
				}
			}
		}
	}
}