Shader "CameraFilterPack/Light_Rainbow" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 55920
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   float _TimeX;
					//   float _Value;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _TimeX       c0       1
					//   _Value       c1       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c2, -0.5, 11.1000004, 0.159154937, 0.5
					    def c3, 6.28318548, -3.14159274, 0.150000006, 0.699999988
					    def c4, 3, 0.25, 0.100000001, 0.166666672
					    def c5, 6, 0, 4, 2
					    def c6, -1, 4.77464819, 0.5, -0.25999999
					    dcl_texcoord_pp v0.xy
					    dcl_2d s0
					    add r0.xyz, c2.x, v0.xyxw
					    mul r0.w, r0.y, c1.x
					    mul r0.x, r0.w, r0.x
					    mov r0.y, c2.y
					    mad r0.x, r0.x, r0.y, c0.x
					    mad r0.x, r0.x, c2.z, c2.w
					    frc r0.x, r0.x
					    mad r0.x, r0.x, c3.x, c3.y
					    sincos r1.y, r0.x
					    mad r0.xy, r1.y, c3.z, r0.zwzw
					    mov r1.y, c4.y
					    mul r0.z, r1.y, c0.x
					    mad r0.x, r0.x, c4.z, r0.z
					    mad r0.xzw, r0.x, c5.x, c5.yyzw
					    mul r1.xyz, r0.xzww, c4.w
					    frc r2.xyz, r1
					    add r1.xyz, r1, -r2
					    mad r0.xzw, r1.xyyz, -c5.x, r0
					    add r0.xzw, r0, -c4.x
					    add_sat r0.xzw, r0_abs, c6.x
					    add r1.x, -r0_abs.y, c3.w
					    mul r0.y, r0.y, r0.y
					    mad r0.y, r0.y, c6.y, c6.z
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c3.x, c3.y
					    sincos r2.y, r0.y
					    mad r0.y, r2.y, c6.w, -c6.x
					    mul_sat r1.x, r1.x, c4.x
					    mul r0.xzw, r0, r1.x
					    texld r1, v0, s0
					    mul r1.xyz, r1, c2.w
					    mad oC0.xyz, r0.xzww, r0.y, r1
					    mov oC0.w, -c6.x
					
					// approximately 47 instruction slots used (1 texture, 46 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _TimeX;
						float _Value;
						vec4 unused_0_3;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					float u_xlat2;
					float u_xlat4;
					void main()
					{
					    u_xlat0.xyz = vs_TEXCOORD0.xyx + vec3(-0.5, -0.5, -0.5);
					    u_xlat0.w = u_xlat0.y * _Value;
					    u_xlat0.x = u_xlat0.w * u_xlat0.x;
					    u_xlat0.x = u_xlat0.x * 11.1000004 + _TimeX;
					    u_xlat0.x = sin(u_xlat0.x);
					    u_xlat0.xy = u_xlat0.xx * vec2(0.150000006, 0.150000006) + u_xlat0.zw;
					    u_xlat4 = _TimeX * 0.25;
					    u_xlat0.x = u_xlat0.x * 0.100000001 + u_xlat4;
					    u_xlat0.xzw = u_xlat0.xxx * vec3(6.0, 6.0, 6.0) + vec3(0.0, 4.0, 2.0);
					    u_xlat1.xyz = u_xlat0.xzw * vec3(0.166666672, 0.166666672, 0.166666672);
					    u_xlat1.xyz = floor(u_xlat1.xyz);
					    u_xlat0.xzw = (-u_xlat1.xyz) * vec3(6.0, 6.0, 6.0) + u_xlat0.xzw;
					    u_xlat0.xzw = u_xlat0.xzw + vec3(-3.0, -3.0, -3.0);
					    u_xlat0.xzw = abs(u_xlat0.xzw) + vec3(-1.0, -1.0, -1.0);
					    u_xlat0.xzw = clamp(u_xlat0.xzw, 0.0, 1.0);
					    u_xlat1.x = -abs(u_xlat0.y) + 0.699999988;
					    u_xlat2 = u_xlat0.y * u_xlat0.y;
					    u_xlat2 = u_xlat2 * 30.0;
					    u_xlat2 = sin(u_xlat2);
					    u_xlat2 = (-u_xlat2) * 0.25999999 + 1.0;
					    u_xlat1.x = u_xlat1.x * 3.0;
					    u_xlat1.x = clamp(u_xlat1.x, 0.0, 1.0);
					    u_xlat0.xzw = u_xlat0.xzw * u_xlat1.xxx;
					    u_xlat1 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat1.xyz = u_xlat1.xyz * vec3(0.5, 0.5, 0.5);
					    SV_Target0.xyz = u_xlat0.xzw * vec3(u_xlat2) + u_xlat1.xyz;
					    SV_Target0.w = 1.0;
					    return;
					}"
				}
			}
		}
	}
}