Shader "CameraFilterPack/FX_Hexagon" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_Distortion ("_Distortion", Range(0, 1)) = 0.3
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 21913
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c0, 36.0828476, 0.5, 0.0320000015, 31.25
					    def c1, 0.0277139992, 0.0160000008, 0, 1
					    def c2, 31.2499981, 0.5, 0.0184760932, 2
					    def c3, 0.0277128126, 0.0320000015, 0.5, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    mul r0.x, c0.x, v0.x
					    frc r0.y, r0.x
					    add r0.xz, -r0.y, r0.x
					    mul r0.w, r0.z, c0.y
					    frc r0.w, r0_abs.w
					    cmp r0.w, r0.z, r0.w, -r0.w
					    mad r0.w, r0.w, -c0.z, v0.y
					    mul r1.x, r0.w, c0.w
					    frc r1.y, r1.x
					    add r0.y, -r1.y, r1.x
					    add r1.xz, r0.z, -c1.w
					    mul r1.w, r1.z, c0.y
					    frc r1.w, r1_abs.w
					    cmp r1.w, r1.z, r1.w, -r1.w
					    mad r1.w, r1.w, -c2.w, r0.y
					    mad r0.w, r0.y, -c0.z, r0.w
					    add r2.x, -r0.w, c1.y
					    mad r0.w, r0.w, -c2.x, c2.y
					    cmp r2.x, r2.x, c1.z, c1.w
					    add r1.y, r1.w, r2.x
					    mad r1.w, r0.z, -c1.x, v0.x
					    mad r0.w, r0_abs.w, c2.z, -r1.w
					    cmp r0.xyz, r0.w, r1, r0
					    mul r1.xyz, r0, c3
					    frc r0.x, r1_abs.z
					    cmp r0.x, r0.z, r0.x, -r0.x
					    mad r1.w, r0.x, c0.z, r1.y
					    texld_pp oC0, r1.xwzw, s0
					
					// approximately 28 instruction slots used (1 texture, 27 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec3 u_xlat1;
					bool u_xlatb1;
					float u_xlat2;
					bool u_xlatb2;
					float u_xlat6;
					float u_xlat9;
					bool u_xlatb9;
					float u_xlat10;
					bool u_xlatb10;
					void main()
					{
					    u_xlat0.x = vs_TEXCOORD0.x * 36.0828476;
					    u_xlat0.xz = floor(u_xlat0.xx);
					    u_xlat1.xz = u_xlat0.zz + vec2(-1.0, -1.0);
					    u_xlat9 = u_xlat1.z * 0.5;
					    u_xlatb10 = u_xlat9>=(-u_xlat9);
					    u_xlat9 = fract(abs(u_xlat9));
					    u_xlat9 = (u_xlatb10) ? u_xlat9 : (-u_xlat9);
					    u_xlat10 = u_xlat0.z * 0.5;
					    u_xlatb2 = u_xlat10>=(-u_xlat10);
					    u_xlat10 = fract(abs(u_xlat10));
					    u_xlat10 = (u_xlatb2) ? u_xlat10 : (-u_xlat10);
					    u_xlat10 = (-u_xlat10) * 0.0320000015 + vs_TEXCOORD0.y;
					    u_xlat2 = u_xlat10 * 31.25;
					    u_xlat0.y = floor(u_xlat2);
					    u_xlat9 = (-u_xlat9) * 2.0 + u_xlat0.y;
					    u_xlat10 = (-u_xlat0.y) * 0.0320000015 + u_xlat10;
					    u_xlatb2 = 0.0160000008<u_xlat10;
					    u_xlat10 = (-u_xlat10) * 31.2499981 + 0.5;
					    u_xlat10 = abs(u_xlat10) * 0.0184760932;
					    u_xlat2 = u_xlatb2 ? 1.0 : float(0.0);
					    u_xlat1.y = u_xlat9 + u_xlat2;
					    u_xlat9 = (-u_xlat0.z) * 0.0277139992 + vs_TEXCOORD0.x;
					    u_xlatb9 = u_xlat10<u_xlat9;
					    u_xlat0.xyz = (bool(u_xlatb9)) ? u_xlat0.xyz : u_xlat1.xyz;
					    u_xlat0.xyz = u_xlat0.xyz * vec3(0.0277128126, 0.0320000015, 0.5);
					    u_xlatb1 = u_xlat0.z>=(-u_xlat0.z);
					    u_xlat6 = fract(abs(u_xlat0.z));
					    u_xlat6 = (u_xlatb1) ? u_xlat6 : (-u_xlat6);
					    u_xlat0.w = u_xlat6 * 0.0320000015 + u_xlat0.y;
					    SV_Target0 = texture(_MainTex, u_xlat0.xw);
					    return;
					}"
				}
			}
		}
	}
}