Shader "CameraFilterPack/Drawing_Manga_Color" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_Distortion ("_Distortion", Range(0, 1)) = 0.3
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
		_DotSize ("_DotSize", Range(0, 1)) = 0
		_ColorLevel ("_ColorLevel", Range(0, 10)) = 7
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 28351
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float _DotSize;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _DotSize     c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 1335.17578, 0.707106411, 480, 0.25
					    def c2, 0.159154937, 0.5, 6.28318548, -3.14159274
					    def c3, 0.112500004, 0.221249998, 0.0412499979, 0.25
					    def c4, 4, -3, 0.0399999991, 0.357142866
					    def c5, 0.501338065, 0.5, 0.125, 0
					    def c6, 0, -1, 0.5, 1.39999998
					    def c7, 0.25, 0.5, 0.001953125, -0.001953125
					    dcl_texcoord_pp v0.xy
					    dcl_2d s0
					    mov r0.zw, c7
					    mad r0.xy, c0.x, r0.zwzw, v0
					    texld r1, r0, s0
					    dp4 r0.x, r1, c3
					    mad r0.yz, c0.x, -r0.z, v0.xxyw
					    texld r1, r0.yzzw, s0
					    dp4 r0.y, r1, c3
					    mad r0.x, r0.x, c4.x, -r0.y
					    mad r0.x, r0.y, c4.y, r0.x
					    mad r0.x, r0.x, -r0.x, c4.z
					    cmp r0.x, r0.x, c6.x, c6.y
					    rcp r0.y, c0.x
					    mul r0.y, r0.y, c1.x
					    mul r1, c1.yyzz, v0.xyxy
					    add r0.zw, r1.xyyw, r1.xyxz
					    mad r1.xy, v0.x, c1.yzzw, -r1.ywzw
					    mul r0.z, r0.y, r0.z
					    mul r0.y, r0.y, r1.x
					    mad r0.y, r0.y, c2.x, c2.y
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c2.z, c2.w
					    sincos r2.x, r0.y
					    mad r0.y, r0.z, c2.x, c2.y
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c2.z, c2.w
					    sincos r3.x, r0.y
					    mad r0.y, r3.x, c7.x, c7.y
					    mad r0.y, r2.x, c1.w, r0.y
					    texld r2, v0, s0
					    add r2, r2.xyzx, r2.xyzx
					    mad r2, r0.x, r0.y, r2
					    mul r3, r2, c6.zzzw
					    mad r0.x, r2.x, c2.y, -r3.y
					    frc r0.y, r3.w
					    add r0.y, -r0.y, r3.w
					    mul r0.y, r0.y, c4.w
					    mul r0.z, r0.w, r0.y
					    mul r0.y, r1.y, r0.y
					    mad r0.y, r0.y, c5.x, c5.y
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c2.z, c2.w
					    sincos r1.y, r0.y
					    mad r0.y, r0.z, c5.x, c5.y
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c2.z, c2.w
					    sincos r2.y, r0.y
					    cmp r0.x, r0.x, r2.y, r1.y
					    mad oC0.xyz, r0.x, -c5.z, r3
					    mov oC0.w, -c6.y
					
					// approximately 77 instruction slots used (3 texture, 74 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[4];
						float _DotSize;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					bool u_xlatb0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					vec2 u_xlat3;
					vec2 u_xlat6;
					bool u_xlatb6;
					void main()
					{
					    u_xlat0.xy = vec2(_DotSize) * vec2(0.001953125, -0.001953125) + vs_TEXCOORD0.xy;
					    u_xlat0 = texture(_MainTex, u_xlat0.xy);
					    u_xlat0.x = dot(u_xlat0, vec4(0.112500004, 0.221249998, 0.0412499979, 0.25));
					    u_xlat3.xy = (-vec2(_DotSize)) * vec2(0.001953125, 0.001953125) + vs_TEXCOORD0.xy;
					    u_xlat1 = texture(_MainTex, u_xlat3.xy);
					    u_xlat3.x = dot(u_xlat1, vec4(0.112500004, 0.221249998, 0.0412499979, 0.25));
					    u_xlat0.x = u_xlat0.x * 4.0 + (-u_xlat3.x);
					    u_xlat0.x = u_xlat3.x * -3.0 + u_xlat0.x;
					    u_xlat0.x = u_xlat0.x * u_xlat0.x;
					    u_xlatb0 = 0.0399999991<u_xlat0.x;
					    u_xlat0.x = u_xlatb0 ? -1.0 : float(0.0);
					    u_xlat3.x = 2136.28125 / _DotSize;
					    u_xlat3.x = u_xlat3.x * 0.625;
					    u_xlat1 = vs_TEXCOORD0.xyxy * vec4(0.707106411, 0.707106411, 480.0, 480.0);
					    u_xlat6.xy = u_xlat1.yw + u_xlat1.xz;
					    u_xlat1.xy = vs_TEXCOORD0.xx * vec2(0.707106411, 480.0) + (-u_xlat1.yw);
					    u_xlat3.y = u_xlat3.x * u_xlat6.x;
					    u_xlat3.x = u_xlat3.x * u_xlat1.x;
					    u_xlat3.xy = cos(u_xlat3.xy);
					    u_xlat6.x = u_xlat3.y * 0.25 + 0.5;
					    u_xlat3.x = u_xlat3.x * 0.25 + u_xlat6.x;
					    u_xlat2 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat2 = u_xlat2.xyzx + u_xlat2.xyzx;
					    u_xlat2 = u_xlat0.xxxx * u_xlat3.xxxx + u_xlat2;
					    u_xlat2 = u_xlat2 * vec4(0.5, 0.5, 0.5, 1.39999998);
					    u_xlat0.x = floor(u_xlat2.w);
					    u_xlat0.x = u_xlat0.x * 0.357142866;
					    u_xlat0.y = u_xlat6.y * u_xlat0.x;
					    u_xlat0.x = u_xlat1.y * u_xlat0.x;
					    u_xlat0.xy = u_xlat0.xy * vec2(3.1500001, 3.1500001);
					    u_xlat0.xy = sin(u_xlat0.xy);
					    u_xlatb6 = u_xlat2.x<u_xlat2.y;
					    u_xlat0.x = (u_xlatb6) ? u_xlat0.x : u_xlat0.y;
					    SV_Target0.xyz = (-u_xlat0.xxx) * vec3(0.125, 0.125, 0.125) + u_xlat2.xyz;
					    SV_Target0.w = 1.0;
					    return;
					}"
				}
			}
		}
	}
}