Shader "CameraFilterPack/FX_Grid" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_Distortion ("_Distortion", Range(0, 5)) = 1
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 22450
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float _Distortion;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Distortion  c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 0.330000013, 0.150000006, 0.300000012, 1
					    def c2, 60, 35.2999992, 0.0166666675, 0.0283286124
					    def c3, 0, 1, 0.5, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    mul r0.xy, c2, v0
					    frc r0.zw, r0.xyyx
					    add r0.xy, -r0.wzzw, r0
					    mov r1.yzw, c1
					    mad r0.zw, c0.x, -r1.y, r0
					    mul r2.xy, r0, c2.zwzw
					    mov r2.zw, v0.xyyx
					    texld r3, r2.wyzw, s0
					    texld r2, r2.xzzw, s0
					    dp3 r0.x, r2, c1.x
					    dp3 r0.y, r3, c1.x
					    mad r1.x, c0.x, -r1.z, r1.w
					    mad r0.z, r1.x, -r0.y, r0.z
					    add r0.y, r0.x, r0.y
					    mad r0.x, r1.x, -r0.x, r0.w
					    mad r0.x, c0.x, -r1.y, r0_abs.x
					    mul r0.y, r0.y, c3.z
					    mad r0.z, c0.x, -r1.y, r0_abs.z
					    cmp r0.xz, r0, c3.x, c3.y
					    add r0.x, r0.x, r0.z
					    cmp r0.xz, -r0.x, c3.xyyw, c3.yyxw
					    mul r0.xy, r0.y, r0.xzzw
					    mad oC0.y, r0.y, c1.z, r0.x
					    mov oC0.xzw, c3.xyxy
					
					// approximately 24 instruction slots used (2 texture, 22 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _Distortion;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec2 u_xlat0;
					bvec2 u_xlatb0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					float u_xlat3;
					vec2 u_xlat6;
					float u_xlat9;
					void main()
					{
					    u_xlat0.xy = vs_TEXCOORD0.xy * vec2(60.0, 35.2999992);
					    u_xlat6.xy = floor(u_xlat0.xy);
					    u_xlat0.xy = fract(u_xlat0.yx);
					    u_xlat0.xy = (-vec2(vec2(_Distortion, _Distortion))) * vec2(0.150000006, 0.150000006) + u_xlat0.xy;
					    u_xlat1.xy = u_xlat6.xy * vec2(0.0166666675, 0.0283286124);
					    u_xlat1.zw = vs_TEXCOORD0.yx;
					    u_xlat2 = texture(_MainTex, u_xlat1.wy);
					    u_xlat1 = texture(_MainTex, u_xlat1.xz);
					    u_xlat6.x = dot(u_xlat1.xyz, vec3(0.330000013, 0.330000013, 0.330000013));
					    u_xlat9 = dot(u_xlat2.xyz, vec3(0.330000013, 0.330000013, 0.330000013));
					    u_xlat1.x = (-_Distortion) * 0.300000012 + 1.0;
					    u_xlat0.x = (-u_xlat1.x) * u_xlat9 + u_xlat0.x;
					    u_xlat9 = u_xlat6.x + u_xlat9;
					    u_xlat0.y = (-u_xlat1.x) * u_xlat6.x + u_xlat0.y;
					    u_xlat6.x = u_xlat9 * 0.5;
					    u_xlat9 = _Distortion * 0.150000006;
					    u_xlatb0.xy = lessThan(abs(u_xlat0.xyxx), vec4(u_xlat9)).xy;
					    u_xlatb0.x = u_xlatb0.y || u_xlatb0.x;
					    u_xlat3 = (u_xlatb0.x) ? 0.0 : 1.0;
					    u_xlat0.x = u_xlatb0.x ? 1.0 : float(0.0);
					    u_xlat3 = u_xlat6.x * u_xlat3;
					    u_xlat3 = u_xlat3 * 0.300000012;
					    SV_Target0.y = u_xlat0.x * u_xlat6.x + u_xlat3;
					    SV_Target0.xzw = vec3(0.0, 0.0, 1.0);
					    return;
					}"
				}
			}
		}
	}
}