Shader "CameraFilterPack/Distortion_Noise" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_Distortion ("_Distortion", Range(0, 1)) = 0.3
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 12462
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float _Distortion;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Distortion  c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 10, 2, 3, 0.00346020004
					    def c2, 0, 1, 34, 289
					    def c3, 0.0243902002, 0.100000001, 0, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    mul r0.xy, c1.x, v0
					    frc r1, r0.xxyy
					    add r0, r0.xxyy, -r1
					    add_pp r1, r0, c2.xyxy
					    mad r0.xy, v0, c1.x, -r0.ywzw
					    mad_pp r2, r1.xyxy, c2.z, c2.y
					    mul_pp r2, r1.xyxy, r2
					    mul_pp r3, r2.zwzw, c1.w
					    frc_pp r4, r3.zwzw
					    add_pp r3, r3, -r4
					    mad_pp r2, r3, -c2.w, r2
					    add_pp r1, r1.zzww, r2
					    mad_pp r2, r1, c2.z, c2.y
					    mul_pp r1, r1, r2
					    mul_pp r2, r1, c1.w
					    frc_pp r3, r2
					    add_pp r2, r2, -r3
					    mad_pp r1, r2, -c2.w, r1
					    mad_pp r2, r1, c2.z, c2.y
					    mul_pp r2, r1, r2
					    add_pp r1, r1, c2.y
					    mul_pp r3, r2, c1.w
					    frc_pp r4, r3
					    add_pp r3, r3, -r4
					    mad_pp r2, r3, -c2.w, r2
					    mul_pp r2, r2, c3.x
					    frc_pp r2, r2
					    mul r0.zw, r0.xyxy, r0.xyxy
					    mad r0.xy, r0, -c1.y, c1.z
					    mul r0.xy, r0, r0.zwzw
					    lrp r3.xy, r0.x, r2.ywzw, r2.xzzw
					    lrp r2.x, r0.y, r3.y, r3.x
					    mad_pp r3, r1, c2.z, c2.y
					    mul_pp r1, r1, r3
					    mul_pp r3, r1, c1.w
					    frc_pp r4, r3
					    add_pp r3, r3, -r4
					    mad_pp r1, r3, -c2.w, r1
					    mul_pp r1, r1, c3.x
					    frc_pp r1, r1
					    lrp r3.xy, r0.x, r1.ywzw, r1.xzzw
					    lrp r2.y, r0.y, r3.y, r3.x
					    mul r0.xy, r2, c0.x
					    mad r0.xy, r0, c3.y, v0
					    texld_pp oC0, r0, s0
					
					// approximately 45 instruction slots used (1 texture, 44 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _Distortion;
						vec4 unused_0_2;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					vec4 u_xlat3;
					vec4 u_xlat4;
					vec2 u_xlat10;
					void main()
					{
					    u_xlat0.xy = vs_TEXCOORD0.xy * vec2(10.0, 10.0);
					    u_xlat0 = floor(u_xlat0.xxyy);
					    u_xlat1 = u_xlat0 + vec4(0.0, 1.0, 0.0, 1.0);
					    u_xlat0.xy = vs_TEXCOORD0.xy * vec2(10.0, 10.0) + (-u_xlat0.yw);
					    u_xlat2 = u_xlat1.xyxy * vec4(34.0, 34.0, 34.0, 34.0) + vec4(1.0, 1.0, 1.0, 1.0);
					    u_xlat2 = u_xlat1.xyxy * u_xlat2;
					    u_xlat3 = u_xlat2.zwzw * vec4(0.00346020004, 0.00346020004, 0.00346020004, 0.00346020004);
					    u_xlat3 = floor(u_xlat3);
					    u_xlat2 = (-u_xlat3) * vec4(289.0, 289.0, 289.0, 289.0) + u_xlat2;
					    u_xlat1 = u_xlat1.zzww + u_xlat2;
					    u_xlat2 = u_xlat1 * vec4(34.0, 34.0, 34.0, 34.0) + vec4(1.0, 1.0, 1.0, 1.0);
					    u_xlat1 = u_xlat1 * u_xlat2;
					    u_xlat2 = u_xlat1 * vec4(0.00346020004, 0.00346020004, 0.00346020004, 0.00346020004);
					    u_xlat2 = floor(u_xlat2);
					    u_xlat1 = (-u_xlat2) * vec4(289.0, 289.0, 289.0, 289.0) + u_xlat1;
					    u_xlat2 = u_xlat1 * vec4(34.0, 34.0, 34.0, 34.0) + vec4(1.0, 1.0, 1.0, 1.0);
					    u_xlat2 = u_xlat1 * u_xlat2;
					    u_xlat1 = u_xlat1 + vec4(1.0, 1.0, 1.0, 1.0);
					    u_xlat3 = u_xlat2 * vec4(0.00346020004, 0.00346020004, 0.00346020004, 0.00346020004);
					    u_xlat3 = floor(u_xlat3);
					    u_xlat2 = (-u_xlat3) * vec4(289.0, 289.0, 289.0, 289.0) + u_xlat2;
					    u_xlat2 = u_xlat2 * vec4(0.0243902002, 0.0243902002, 0.0243902002, 0.0243902002);
					    u_xlat2 = fract(u_xlat2);
					    u_xlat10.xy = u_xlat0.xy * u_xlat0.xy;
					    u_xlat0.xy = (-u_xlat0.xy) * vec2(2.0, 2.0) + vec2(3.0, 3.0);
					    u_xlat3.xy = (-u_xlat10.xy) * u_xlat0.xy + vec2(1.0, 1.0);
					    u_xlat0.xy = u_xlat0.xy * u_xlat10.xy;
					    u_xlat10.xy = u_xlat2.xz * u_xlat3.xx;
					    u_xlat10.xy = u_xlat2.yw * u_xlat0.xx + u_xlat10.xy;
					    u_xlat10.x = u_xlat3.y * u_xlat10.x;
					    u_xlat2.x = u_xlat10.y * u_xlat0.y + u_xlat10.x;
					    u_xlat4 = u_xlat1 * vec4(34.0, 34.0, 34.0, 34.0) + vec4(1.0, 1.0, 1.0, 1.0);
					    u_xlat1 = u_xlat1 * u_xlat4;
					    u_xlat4 = u_xlat1 * vec4(0.00346020004, 0.00346020004, 0.00346020004, 0.00346020004);
					    u_xlat4 = floor(u_xlat4);
					    u_xlat1 = (-u_xlat4) * vec4(289.0, 289.0, 289.0, 289.0) + u_xlat1;
					    u_xlat1 = u_xlat1 * vec4(0.0243902002, 0.0243902002, 0.0243902002, 0.0243902002);
					    u_xlat1 = fract(u_xlat1);
					    u_xlat10.xy = u_xlat3.xx * u_xlat1.xz;
					    u_xlat0.xz = u_xlat1.yw * u_xlat0.xx + u_xlat10.xy;
					    u_xlat0.x = u_xlat3.y * u_xlat0.x;
					    u_xlat2.y = u_xlat0.z * u_xlat0.y + u_xlat0.x;
					    u_xlat0.xy = u_xlat2.xy * vec2(vec2(_Distortion, _Distortion));
					    u_xlat0.xy = u_xlat0.xy * vec2(0.100000001, 0.100000001) + vs_TEXCOORD0.xy;
					    SV_Target0 = texture(_MainTex, u_xlat0.xy);
					    return;
					}"
				}
			}
		}
	}
}