Shader "CameraFilterPack/Blend2Camera_Color" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_MainTex2 ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 42426
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   sampler2D _MainTex2;
					//   float2 _MainTex_TexelSize;
					//   float _Value;
					//   float _Value2;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _Value             c0       1
					//   _Value2            c1       1
					//   _MainTex_TexelSize c2       1
					//   _MainTex           s0       1
					//   _MainTex2          s1       1
					//
					
					    ps_3_0
					    def c3, 6, 1.00000001e-010, -3, 0
					    def c4, 1, 0.666666687, 0.333333343, 0
					    def c5, 1, 0, -1, 0.666666687
					    def c6, 1, 0, -0.333333343, 1.00000001e-010
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    dcl_2d s1
					    add r0.x, c6.x, -v0.y
					    cmp r0.y, c2.y, v0.y, r0.x
					    mov r0.x, v0.x
					    texld r0, r0, s1
					    texld r1, v0, s0
					    lrp r2.xyz, c1.x, r0, r1
					    add r0.xyz, r0, -r1
					    mad r3, r2.yzyy, c6.xxyy, c6.yyyz
					    mad r4, r3.yxyy, c5.xxyy, c5.yyzw
					    add r0.w, -r2.z, r2.y
					    cmp r3, r0.w, r3.xywz, r4.xywz
					    add r0.w, r2.x, -r3.x
					    mov r4.x, r2.x
					    mov r4.yzw, r3.xywx
					    mov r3.xyw, r4.wyzx
					    cmp r3, r0.w, r4, r3
					    min r0.w, r3.y, r3.w
					    add r0.w, -r0.w, r3.x
					    mad r1.w, r0.w, c3.x, c3.y
					    rcp r1.w, r1.w
					    add r2.w, -r3.y, r3.w
					    mad r1.w, r2.w, r1.w, r3.z
					    add r2.w, r3.x, c6.w
					    rcp r2.w, r2.w
					    mul r0.w, r0.w, r2.w
					    add r3.xyz, r1_abs.w, c4
					    frc r3.xyz, r3
					    mad r3.xyz, r3, c3.x, c3.z
					    add_sat r3.xyz, r3_abs, -c6.x
					    lrp r4.xyz, r0.w, r3, c6.x
					    mov r3.x, c6.x
					    add r0.w, r3.x, -c1.x
					    mad r0.xyz, r0.w, r0, r1
					    max r1.x, r0.y, r0.z
					    max r2.w, r0.x, r1.x
					    mad r0.xyz, r2.w, r4, -r2
					    mad oC0.xyz, c0.x, r0, r2
					    mov oC0.w, c6.x
					
					// approximately 38 instruction slots used (2 texture, 36 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _Value;
						float _Value2;
						vec4 unused_0_3;
						vec2 _MainTex_TexelSize;
					};
					uniform  sampler2D _MainTex;
					uniform  sampler2D _MainTex2;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					bool u_xlatb2;
					vec4 u_xlat3;
					vec3 u_xlat4;
					vec3 u_xlat5;
					float u_xlat6;
					bool u_xlatb6;
					float u_xlat7;
					float u_xlat15;
					bool u_xlatb15;
					float u_xlat17;
					bool u_xlatb17;
					void main()
					{
					    u_xlat0.z = float(-1.0);
					    u_xlat0.w = float(0.666666687);
					    u_xlat1.z = float(1.0);
					    u_xlat1.w = float(-1.0);
					    u_xlatb2 = _MainTex_TexelSize.y<0.0;
					    u_xlat7 = (-vs_TEXCOORD0.y) + 1.0;
					    u_xlat2.y = (u_xlatb2) ? u_xlat7 : vs_TEXCOORD0.y;
					    u_xlat2.x = vs_TEXCOORD0.x;
					    u_xlat2 = texture(_MainTex2, u_xlat2.xy);
					    u_xlat3 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat2.xyz = u_xlat2.xyz + (-u_xlat3.xyz);
					    u_xlat4.xyz = vec3(vec3(_Value2, _Value2, _Value2)) * u_xlat2.xyz + u_xlat3.xyz;
					    u_xlatb17 = u_xlat4.y>=u_xlat4.z;
					    u_xlat17 = u_xlatb17 ? 1.0 : float(0.0);
					    u_xlat0.xy = u_xlat4.zy;
					    u_xlat1.xy = (-u_xlat0.xy) + u_xlat4.yz;
					    u_xlat0 = vec4(u_xlat17) * u_xlat1.xywz + u_xlat0.xywz;
					    u_xlat1.z = u_xlat0.w;
					    u_xlatb17 = u_xlat4.x>=u_xlat0.x;
					    u_xlat17 = u_xlatb17 ? 1.0 : float(0.0);
					    u_xlat0.w = u_xlat4.x;
					    u_xlat1.xyw = u_xlat0.wyx;
					    u_xlat1 = (-u_xlat0) + u_xlat1;
					    u_xlat0 = vec4(u_xlat17) * u_xlat1 + u_xlat0;
					    u_xlat1.x = min(u_xlat0.y, u_xlat0.w);
					    u_xlat1.x = u_xlat0.x + (-u_xlat1.x);
					    u_xlat6 = u_xlat1.x * 6.0 + 1.00000001e-10;
					    u_xlat5.x = (-u_xlat0.y) + u_xlat0.w;
					    u_xlat5.x = u_xlat5.x / u_xlat6;
					    u_xlat5.x = u_xlat5.x + u_xlat0.z;
					    u_xlat0.x = u_xlat0.x + 1.00000001e-10;
					    u_xlat0.x = u_xlat1.x / u_xlat0.x;
					    u_xlat5.xyz = abs(u_xlat5.xxx) + vec3(1.0, 0.666666687, 0.333333343);
					    u_xlat5.xyz = fract(u_xlat5.xyz);
					    u_xlat5.xyz = u_xlat5.xyz * vec3(6.0, 6.0, 6.0) + vec3(-3.0, -3.0, -3.0);
					    u_xlat5.xyz = abs(u_xlat5.xyz) + vec3(-1.0, -1.0, -1.0);
					    u_xlat5.xyz = clamp(u_xlat5.xyz, 0.0, 1.0);
					    u_xlat5.xyz = u_xlat5.xyz + vec3(-1.0, -1.0, -1.0);
					    u_xlat0.xyz = u_xlat0.xxx * u_xlat5.xyz + vec3(1.0, 1.0, 1.0);
					    u_xlat15 = (-_Value2) + 1.0;
					    u_xlat1.xyz = vec3(u_xlat15) * u_xlat2.xyz + u_xlat3.xyz;
					    u_xlatb15 = u_xlat1.y>=u_xlat1.z;
					    u_xlat15 = u_xlatb15 ? 1.0 : float(0.0);
					    u_xlat6 = (-u_xlat1.z) + u_xlat1.y;
					    u_xlat15 = u_xlat15 * u_xlat6 + u_xlat1.z;
					    u_xlatb6 = u_xlat1.x>=u_xlat15;
					    u_xlat1.x = (-u_xlat15) + u_xlat1.x;
					    u_xlat6 = u_xlatb6 ? 1.0 : float(0.0);
					    u_xlat15 = u_xlat6 * u_xlat1.x + u_xlat15;
					    u_xlat0.xyz = vec3(u_xlat15) * u_xlat0.xyz + (-u_xlat4.xyz);
					    SV_Target0.xyz = vec3(vec3(_Value, _Value, _Value)) * u_xlat0.xyz + u_xlat4.xyz;
					    SV_Target0.w = 1.0;
					    return;
					}"
				}
			}
		}
	}
}