Shader "CameraFilterPack/Distortion_Water_Drop" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_Distortion ("_Distortion", Range(0, 1)) = 0.3
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
		_CenterX ("_CenterX", Range(-1, 1)) = 0
		_CenterY ("_CenterY", Range(-1, 1)) = 0
		_WaveIntensity ("_WaveIntensity", Range(0, 10)) = 0
		_NumberOfWaves ("_NumberOfWaves", Range(0, 10)) = 0
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 58145
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float _CenterX;
					//   float _CenterY;
					//   sampler2D _MainTex;
					//   int _NumberOfWaves;
					//   float _TimeX;
					//   float _WaveIntensity;
					//
					//
					// Registers:
					//
					//   Name           Reg   Size
					//   -------------- ----- ----
					//   _TimeX         c0       1
					//   _CenterX       c1       1
					//   _CenterY       c2       1
					//   _WaveIntensity c3       1
					//   _NumberOfWaves c4       1
					//   _MainTex       s0       1
					//
					
					    ps_3_0
					    def c5, 3, -5, 0.5, 0
					    def c6, 8, 0.159154937, 0.5, 1
					    def c7, 6.28318548, -3.14159274, 0.5, -0.300000012
					    def c8, 0.333333343, 5, 1, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    mov r0.xyz, c5
					    mad r0.w, c1.x, r0.z, r0.z
					    mad r0.z, c2.x, -r0.z, r0.z
					    mov r1.xy, -r0.wzzw
					    add r0.zw, r1.xyxy, v0.xyxy
					    dp2add r1.x, r0.zwzw, r0.zwzw, c5.w
					    rsq r1.x, r1.x
					    rcp r1.y, r1.x
					    mul r0.zw, r0, r1.x
					    add r0.x, r0.x, c4.x
					    mul r0.x, r0.x, r1.y
					    mad r1.x, r1.y, c8.y, c8.z
					    rcp r1.x, r1.x
					    mul r0.y, r0.y, c0.x
					    mad r0.x, r0.x, c6.x, r0.y
					    mad r0.x, r0.x, c6.y, c6.z
					    frc r0.x, r0.x
					    mad r0.x, r0.x, c7.x, c7.y
					    sincos r2.y, r0.x
					    add r0.x, r2.y, c6.w
					    mad r0.x, r0.x, c7.z, c7.w
					    mul r0.y, r0.x, r0.x
					    mul r0.x, r0.y, r0.x
					    mul r0.x, r0.x, c3.x
					    mul r0.x, r0.x, c8.x
					    mul r0.xy, r0.x, -r0.zwzw
					    mad r0.xy, r0, r1.x, v0
					    texld oC0, r0, s0
					
					// approximately 36 instruction slots used (1 texture, 35 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _TimeX;
						vec4 unused_0_2;
						float _CenterX;
						float _CenterY;
						float _WaveIntensity;
						int _NumberOfWaves;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec2 u_xlat0;
					int u_xlati0;
					vec2 u_xlat1;
					vec2 u_xlat2;
					float u_xlat6;
					void main()
					{
					    u_xlati0 = _NumberOfWaves + 3;
					    u_xlat0.x = float(u_xlati0);
					    u_xlat2.x = _CenterX * 0.5 + 0.5;
					    u_xlat1.x = (-u_xlat2.x);
					    u_xlat2.x = (-_CenterY) * 0.5 + 0.5;
					    u_xlat1.y = (-u_xlat2.x);
					    u_xlat2.xy = u_xlat1.xy + vs_TEXCOORD0.xy;
					    u_xlat6 = dot(u_xlat2.xy, u_xlat2.xy);
					    u_xlat1.x = sqrt(u_xlat6);
					    u_xlat6 = inversesqrt(u_xlat6);
					    u_xlat2.xy = vec2(u_xlat6) * u_xlat2.xy;
					    u_xlat0.x = u_xlat0.x * u_xlat1.x;
					    u_xlat6 = u_xlat1.x * 5.0 + 1.0;
					    u_xlat1.x = _TimeX * -5.0;
					    u_xlat0.x = u_xlat0.x * 8.0 + u_xlat1.x;
					    u_xlat0.x = sin(u_xlat0.x);
					    u_xlat0.x = u_xlat0.x + 1.0;
					    u_xlat0.x = u_xlat0.x * 0.5 + -0.300000012;
					    u_xlat1.x = u_xlat0.x * u_xlat0.x;
					    u_xlat0.x = u_xlat0.x * u_xlat1.x;
					    u_xlat0.x = u_xlat0.x * _WaveIntensity;
					    u_xlat0.x = u_xlat0.x * 0.333333343;
					    u_xlat0.xy = u_xlat0.xx * (-u_xlat2.xy);
					    u_xlat0.xy = u_xlat0.xy / vec2(u_xlat6);
					    u_xlat0.xy = u_xlat0.xy + vs_TEXCOORD0.xy;
					    SV_Target0 = texture(_MainTex, u_xlat0.xy);
					    return;
					}"
				}
			}
		}
	}
}