Shader "CameraFilterPack/Distortion_ShockWave" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 60883
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   float _TimeX;
					//   float _Value;
					//   float _Value2;
					//   float _Value3;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _TimeX       c0       1
					//   _Value       c1       1
					//   _Value2      c2       1
					//   _Value3      c3       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c4, 0, 0.100000001, -0.100000001, 1
					    def c5, 10, 0.800000012, 40, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    mov r0.x, -c1.x
					    mov r0.y, -c2.x
					    add r0.xy, r0, v0
					    dp2add r0.z, r0, r0, c4.x
					    rsq r0.z, r0.z
					    mul r0.xy, r0.z, r0
					    rcp r0.z, r0.z
					    mov r1.x, c0.x
					    mul r0.w, r1.x, c3.x
					    frc r1.y, r0.w
					    add r1.y, r0.w, -r1.y
					    mad r1.x, r1.x, c3.x, -r1.y
					    rcp r1.y, r0.w
					    mul r1.x, r1.y, r1.x
					    mad r1.y, r0.w, -r1.x, r0.z
					    mul r1.z, r1.y, c5.x
					    pow r2.x, r1_abs.z, c5.y
					    add r2.z, -r2.x, c4.w
					    mul r1.y, r1.y, r2.z
					    mul r0.xy, r0, r1.y
					    mul r1.y, r0.w, r1.x
					    mad r1.xz, r0.w, r1.x, c4.yyzw
					    mul r0.w, r0.z, r1.y
					    mul r0.w, r0.w, c5.z
					    rcp r0.w, r0.w
					    mad r2.xy, r0, r0.w, v0
					    mad r3.xyz, v0.xyxw, c4.wwxw, c4.xxww
					    add r0.x, r0.z, -r1.z
					    add r0.y, -r0.z, r1.x
					    cmp r0.x, r0.x, c4.w, c4.x
					    cmp r0.x, r0.y, r0.x, c4.x
					    cmp r1.xyz, -r0.x, r3, r2
					    texld r2, r1, s0
					    mul r1, r1.z, r2
					    mul r1, r0.w, r1
					    mad oC0, r1, r0.x, r2
					
					// approximately 39 instruction slots used (1 texture, 38 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _TimeX;
						float _Value;
						float _Value2;
						float _Value3;
						vec4 unused_0_5;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					bool u_xlatb0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					vec4 u_xlat3;
					bool u_xlatb4;
					vec2 u_xlat5;
					float u_xlat8;
					float u_xlat12;
					void main()
					{
					    u_xlat0.xy = vs_TEXCOORD0.xy + (-vec2(_Value, _Value2));
					    u_xlat8 = dot(u_xlat0.xy, u_xlat0.xy);
					    u_xlat12 = inversesqrt(u_xlat8);
					    u_xlat8 = sqrt(u_xlat8);
					    u_xlat0.xy = vec2(u_xlat12) * u_xlat0.xy;
					    u_xlat12 = _Value3 * _TimeX;
					    u_xlat12 = floor(u_xlat12);
					    u_xlat12 = _TimeX * _Value3 + (-u_xlat12);
					    u_xlat1.x = (-u_xlat12) + u_xlat8;
					    u_xlat5.x = u_xlat1.x * 10.0;
					    u_xlat5.x = log2(abs(u_xlat5.x));
					    u_xlat5.x = u_xlat5.x * 0.800000012;
					    u_xlat5.x = exp2(u_xlat5.x);
					    u_xlat2.z = (-u_xlat5.x) + 1.0;
					    u_xlat1.x = u_xlat1.x * u_xlat2.z;
					    u_xlat0.xy = u_xlat0.xy * u_xlat1.xx;
					    u_xlat1.x = u_xlat8 * u_xlat12;
					    u_xlat5.xy = vec2(u_xlat12) + vec2(0.100000001, -0.100000001);
					    u_xlat12 = u_xlat1.x * 40.0;
					    u_xlat0.xy = u_xlat0.xy / vec2(u_xlat12);
					    u_xlat2.xy = u_xlat0.xy + vs_TEXCOORD0.xy;
					    u_xlat2.w = 1.0;
					    u_xlat3.xy = vs_TEXCOORD0.xy;
					    u_xlat3.z = float(1.0);
					    u_xlat3.w = float(0.0);
					    u_xlatb0 = u_xlat5.x>=u_xlat8;
					    u_xlatb4 = u_xlat8>=u_xlat5.y;
					    u_xlatb0 = u_xlatb4 && u_xlatb0;
					    u_xlat1 = (bool(u_xlatb0)) ? u_xlat2 : u_xlat3;
					    u_xlat2 = texture(_MainTex, u_xlat1.xy);
					    u_xlat3 = u_xlat1.zzzz * u_xlat2;
					    u_xlat0 = u_xlat3 / vec4(u_xlat12);
					    SV_Target0 = u_xlat0 * u_xlat1.wwww + u_xlat2;
					    return;
					}"
				}
			}
		}
	}
}