Shader "CameraFilterPack/FX_Screens" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 51162
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   float _TimeX;
					//   float _Value;
					//   float _Value2;
					//   float _Value3;
					//   float _Value4;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _TimeX       c0       1
					//   _Value       c1       1
					//   _Value2      c2       1
					//   _Value3      c3       1
					//   _Value4      c4       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c5, 1, 3, -1.79999995, 0.100000001
					    def c6, 2, -0.5, 0, 12
					    def c7, 0.699999988, 1.60000002, 2.79999995, 1
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    mul r0.xy, c1.x, v0
					    frc r0.zw, r0.xyxy
					    add r0.xy, -r0.zwzw, r0
					    rcp r0.z, c1.x
					    mul r0.yz, r0.z, r0.xxyw
					    mad r0.x, v0.x, c1.x, -r0.x
					    add r0.x, r0.x, c6.y
					    texld r1, r0.yzzw, s0
					    add r0.y, r1.y, r1.x
					    add r0.y, r1.z, r0.y
					    mov r1.x, c0.x
					    mad r0.y, r1.x, c2.x, r0.y
					    frc r0.z, r0.y
					    add r0.z, -r0.z, r0.y
					    add r0.y, -r0.z, r0.y
					    add r0.y, -r0.y, c5.x
					    mad r0.y, r0.y, c5.y, c5.z
					    max r1.x, c5.w, r0.y
					    min r0.y, r1.x, c6.x
					    mov r1.x, -c3.x
					    mov r1.y, -c4.x
					    mad r0.xz, r0.x, r0.x, r1.xyyw
					    dp2add r0.x, r0.xzzw, r0.xzzw, c6.z
					    mul r0.x, r0.x, c6.w
					    min r1.x, r0.x, c5.x
					    mad r0.x, r1.x, -r1.x, c5.x
					    mul r0.x, r0.x, r0.y
					    texld r1, v0, s0
					    mad oC0, r0.x, c7, r1
					
					// approximately 30 instruction slots used (2 texture, 28 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _TimeX;
						float _Value;
						float _Value2;
						float _Value3;
						float _Value4;
						vec4 unused_0_6;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec3 u_xlat0;
					vec4 u_xlat1;
					vec2 u_xlat2;
					float u_xlat4;
					void main()
					{
					    u_xlat0.xy = vs_TEXCOORD0.xy * vec2(vec2(_Value, _Value));
					    u_xlat0.xy = floor(u_xlat0.xy);
					    u_xlat2.xy = u_xlat0.xy / vec2(vec2(_Value, _Value));
					    u_xlat0.x = vs_TEXCOORD0.x * _Value + (-u_xlat0.x);
					    u_xlat0.x = u_xlat0.x + -0.5;
					    u_xlat1 = texture(_MainTex, u_xlat2.xy);
					    u_xlat2.x = u_xlat1.y + u_xlat1.x;
					    u_xlat2.x = u_xlat1.z + u_xlat2.x;
					    u_xlat2.x = _TimeX * _Value2 + u_xlat2.x;
					    u_xlat4 = floor(u_xlat2.x);
					    u_xlat2.x = (-u_xlat4) + u_xlat2.x;
					    u_xlat2.x = (-u_xlat2.x) + 1.0;
					    u_xlat2.x = u_xlat2.x * 3.0 + -1.79999995;
					    u_xlat2.x = max(u_xlat2.x, 0.100000001);
					    u_xlat2.x = min(u_xlat2.x, 2.0);
					    u_xlat1.x = (-_Value3);
					    u_xlat1.y = (-_Value4);
					    u_xlat0.xz = u_xlat0.xx * u_xlat0.xx + u_xlat1.xy;
					    u_xlat0.x = dot(u_xlat0.xz, u_xlat0.xz);
					    u_xlat0.x = u_xlat0.x * 12.0;
					    u_xlat0.x = min(u_xlat0.x, 1.0);
					    u_xlat0.x = (-u_xlat0.x) * u_xlat0.x + 1.0;
					    u_xlat0.x = u_xlat0.x * u_xlat2.x;
					    u_xlat1 = texture(_MainTex, vs_TEXCOORD0.xy);
					    SV_Target0 = u_xlat0.xxxx * vec4(0.699999988, 1.60000002, 2.79999995, 1.0) + u_xlat1;
					    return;
					}"
				}
			}
		}
	}
}