Shader "CameraFilterPack/FX_Plasma" {
	Properties {
		_MainTex ("Base (RGB)", 2D) = "white" {}
		_TimeX ("Time", Range(0, 1)) = 1
		_ScreenResolution ("_ScreenResolution", Vector) = (0,0,0,0)
	}
	SubShader {
		Pass {
			ZClip Off
			ZTest Always
			GpuProgramID 44293
			Program "vp" {
				SubProgram "d3d9 " {
					"vs_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   row_major float4x4 glstate_matrix_mvp;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   glstate_matrix_mvp c0       4
					//
					
					    vs_3_0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_texcoord o0.xy
					    dcl_position o1
					    dcl_color o2
					    dp4 r0.x, c0, v0
					    dp4 r0.y, c1, v0
					    dp4 r0.z, c2, v0
					    dp4 r0.w, c3, v0
					    mov o0.xy, v2
					    mov o2, v1
					    mad o1.xy, r0.w, c255, r0
					    mov o1.zw, r0
					
					// approximately 8 instruction slots used"
				}
				SubProgram "d3d11 " {
					"vs_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform UnityPerDraw {
						mat4x4 glstate_matrix_mvp;
						vec4 unused_0_1[18];
					};
					in  vec4 in_POSITION0;
					in  vec4 in_COLOR0;
					in  vec2 in_TEXCOORD0;
					out vec2 vs_TEXCOORD0;
					out vec4 vs_COLOR0;
					vec4 u_xlat0;
					void main()
					{
					    vs_TEXCOORD0.xy = in_TEXCOORD0.xy;
					    u_xlat0 = in_POSITION0.yyyy * glstate_matrix_mvp[1];
					    u_xlat0 = glstate_matrix_mvp[0] * in_POSITION0.xxxx + u_xlat0;
					    u_xlat0 = glstate_matrix_mvp[2] * in_POSITION0.zzzz + u_xlat0;
					    gl_Position = glstate_matrix_mvp[3] * in_POSITION0.wwww + u_xlat0;
					    vs_COLOR0 = in_COLOR0;
					    return;
					}"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					"ps_3_0
					
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//   float _TimeX;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _TimeX       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 6.28318548, -3.14159274, 20, 1000
					    def c2, 22, 800, 0.00499999989, 0.00100000005
					    def c3, 0, 1, 0, 0
					    def c4, 0.00159154937, 0.00318309874, 0.5, 5
					    def c5, 5, 3, 0.100000001, 0.0900000036
					    def c6, 0.0175070427, 0.0238732416, 0.5, 0.159154937
					    def c7, -0.5, 0.5, 0.0318309888, 0
					    def c8, 0.0795774683, 0.0397887342, 0.5, 0.00999999978
					    def c9, 0.00795774721, 0.0159154944, 0.00636619749, 0.5
					    def c10, 0.00557042286, 0.0159154944, 0.5, 0.795774698
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    mad r0.xy, v0.y, c8, c8.z
					    frc r0.xy, r0
					    mad r0.xy, r0, c1.x, c1.y
					    sincos r1.y, r0.x
					    sincos r2.y, r0.y
					    mov r0.xyz, c6
					    mad r0.xy, c0.x, r0, r0.z
					    frc r0.xy, r0
					    mad r0.xy, r0, c1.x, c1.y
					    sincos r3.y, r0.y
					    sincos r4.y, r0.x
					    mad r0.x, r4.y, c1.z, c1.w
					    mad r0.y, r3.y, c2.x, c2.y
					    mad r0.zw, v0.x, c5.xyxy, r0.y
					    mad r0.zw, r0, c6.w, c6.z
					    frc r0.zw, r0
					    mad r0.zw, r0, c1.x, c1.y
					    sincos r3.y, r0.z
					    sincos r4.y, r0.w
					    mad r0.z, r4.y, c8.w, r2.y
					    mul r0.z, r0.z, r0.y
					    mad r1.xzw, r0.y, c9.xyyz, c9.w
					    frc r1.xzw, r1
					    mad r1.xzw, r1, c1.x, c1.y
					    mad r0.y, r0.z, c6.w, c6.z
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c1.x, c1.y
					    sincos r2.y, r0.y
					    mad r0.y, r3.y, c8.w, r1.y
					    mul r0.y, r0.y, r0.x
					    mad r0.y, r0.y, c6.w, c6.z
					    frc r0.y, r0.y
					    mad r0.y, r0.y, c1.x, c1.y
					    sincos r3.y, r0.y
					    mad r0.yz, r0.x, c4.xxyw, c4.z
					    frc r0.yz, r0
					    mad r0.yz, r0, c1.x, c1.y
					    sincos r4.x, r0.y
					    sincos r5.x, r0.z
					    mad r6, r0.x, c2.zwwz, v0.xyxy
					    mad r6, r6, c6.w, c6.z
					    frc r6, r6
					    mad r6, r6, c1.x, c1.y
					    sincos r7.y, r6.x
					    mul r4.x, r4.x, r7.y
					    sincos r7.x, r6.y
					    mul r4.y, r5.x, r7.x
					    mul r0.yz, r4.xxyw, c4.w
					    texld r4, r0.yzzw, s0
					    mul r0.y, r3.y, r4.x
					    sincos r3.y, r6.z
					    sincos r5.x, r6.w
					    mov r5.y, r5.x
					    mov r5.x, r3.y
					    texld r3, r5, s0
					    mul r0.z, r0.x, r3.x
					    mul r0.zw, r0.z, c5
					    sincos r5.y, r1.x
					    add r1.x, -r5.y, v0.x
					    mul r0.z, r0.z, r1.x
					    sincos r5.y, r1.z
					    sincos r6.y, r1.w
					    add r1.x, -r6.y, v0.x
					    mul r0.w, r0.w, r1.x
					    mad r1.xy, r0.x, c10, c10.z
					    frc r1.xy, r1
					    mad r1.xy, r1, c1.x, c1.y
					    sincos r6.y, r1.x
					    sincos r7.y, r1.y
					    add r1.xy, -r7.y, v0
					    add r1.z, -r6.y, v0.y
					    mad r1.z, r1.z, c10.w, c10.z
					    frc r1.z, r1.z
					    mad r1.z, r1.z, c1.x, c1.y
					    sincos r6.y, r1.z
					    mad r0.z, r0.z, r6.y, r5.y
					    mad r0.w, r0.w, r6.y, r5.y
					    mad r0.w, r0.w, c6.w, c6.z
					    frc r0.w, r0.w
					    mad r0.w, r0.w, c1.x, c1.y
					    sincos r5.y, r0.w
					    mad r0.z, r0.z, c6.w, c6.z
					    frc r0.z, r0.z
					    mad r0.z, r0.z, c1.x, c1.y
					    sincos r6.y, r0.z
					    mul r0.y, r0.y, r6.y
					    add r0.zw, c7.xyxy, v0.xyxy
					    mul r0.z, r0.z, r0.x
					    mul r0.x, r0.x, r1.x
					    mad r1.x, r1.y, c6.w, c6.z
					    frc r1.x, r1.x
					    mad r1.x, r1.x, c1.x, c1.y
					    sincos r6.y, r1.x
					    mul r0.x, r0.x, r6.y
					    mad r0.x, r0.x, c7.z, c7.y
					    frc r0.x, r0.x
					    mad r0.x, r0.x, c1.x, c1.y
					    sincos r1.y, r0.x
					    mad r0.x, r0.w, c6.w, c6.z
					    frc r0.x, r0.x
					    mad r0.x, r0.x, c1.x, c1.y
					    sincos r6.y, r0.x
					    mul r0.x, r0.z, r6.y
					    mad r0.x, r0.x, c6.w, c6.z
					    frc r0.x, r0.x
					    mad r0.x, r0.x, c1.x, c1.y
					    sincos r6.y, r0.x
					    mul r0.x, r3.x, r6_abs.y
					    mul r0.x, r0.x, c6.z
					    mad r0.y, r0.y, c6.z, r0.x
					    mul r0.z, r1.y, r4.x
					    mul r0.w, r1_abs.y, r4.x
					    mul r1.x, r2.y, r4.x
					    mul r1.x, r5_abs.y, r1.x
					    mad r0.x, r1.x, c6.z, r0.x
					    mad r1.z, r0.w, c5.z, r0.x
					    mad r1.y, r0.z, c5.z, r0.y
					    texld r0, v0, s0
					    mov r1.xw, c3.xyzy
					    add oC0, r0, r1
					
					// approximately 302 instruction slots used (3 texture, 299 arithmetic)"
				}
				SubProgram "d3d11 " {
					"ps_4_0
					
					#version 330
					#extension GL_ARB_explicit_attrib_location : require
					#extension GL_ARB_explicit_uniform_location : require
					
					#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
					#if HLSLCC_ENABLE_UNIFORM_BUFFERS
					#define UNITY_UNIFORM
					#else
					#define UNITY_UNIFORM uniform
					#endif
					#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
					#if UNITY_SUPPORTS_UNIFORM_LOCATION
					#define UNITY_LOCATION(x) layout(location = x)
					#define UNITY_BINDING(x) layout(binding = x, std140)
					#else
					#define UNITY_LOCATION(x)
					#define UNITY_BINDING(x) layout(std140)
					#endif
					layout(std140) uniform PGlobals {
						vec4 unused_0_0[2];
						float _TimeX;
						vec4 unused_0_2;
					};
					uniform  sampler2D _MainTex;
					in  vec2 vs_TEXCOORD0;
					layout(location = 0) out vec4 SV_Target0;
					vec4 u_xlat0;
					vec4 u_xlat1;
					vec4 u_xlat2;
					vec4 u_xlat3;
					vec4 u_xlat4;
					vec4 u_xlat5;
					float u_xlat6;
					float u_xlat7;
					vec2 u_xlat12;
					float u_xlat18;
					void main()
					{
					    u_xlat0.xy = vs_TEXCOORD0.yy * vec2(0.5, 0.25);
					    u_xlat1 = vec4(_TimeX) * vec4(0.109999999, 0.150000006, 0.109999999, 0.150000006);
					    u_xlat1 = sin(u_xlat1);
					    u_xlat1 = u_xlat1 * vec4(20.0, 22.0, 20.0, 22.0) + vec4(1000.0, 800.0, 1000.0, 800.0);
					    u_xlat0.zw = vs_TEXCOORD0.xx * vec2(5.0, 3.0) + u_xlat1.ww;
					    u_xlat0 = sin(u_xlat0);
					    u_xlat0.xy = u_xlat0.zw * vec2(0.00999999978, 0.00999999978) + u_xlat0.xy;
					    u_xlat0.xy = u_xlat0.xy * u_xlat1.zw;
					    u_xlat0.xy = sin(u_xlat0.xy);
					    u_xlat12.xy = u_xlat1.zz * vec2(0.00999999978, 0.0199999996);
					    u_xlat12.xy = cos(u_xlat12.xy);
					    u_xlat2 = u_xlat1.zzzz * vec4(0.00499999989, 0.00100000005, 0.00100000005, 0.00499999989) + vs_TEXCOORD0.xyxy;
					    u_xlat3.xy = sin(u_xlat2.xz);
					    u_xlat3.zw = cos(u_xlat2.yw);
					    u_xlat12.xy = u_xlat12.xy * u_xlat3.xz;
					    u_xlat2 = texture(_MainTex, u_xlat3.yw);
					    u_xlat12.xy = u_xlat12.xy * vec2(5.0, 5.0);
					    u_xlat3 = texture(_MainTex, u_xlat12.xy);
					    u_xlat0.xy = u_xlat0.xy * u_xlat3.xx;
					    u_xlat12.x = u_xlat1.z * u_xlat2.x;
					    u_xlat12.x = u_xlat12.x * 0.0900000036;
					    u_xlat18 = u_xlat1.w * 0.0399999991;
					    u_xlat18 = sin((-u_xlat18));
					    u_xlat18 = u_xlat18 + vs_TEXCOORD0.x;
					    u_xlat12.x = u_xlat18 * u_xlat12.x;
					    u_xlat4 = u_xlat1 * vec4(0.100000001, 0.0500000007, 0.0350000001, 0.100000001);
					    u_xlat5 = sin((-u_xlat4.yzxx));
					    u_xlat5 = u_xlat5 + vs_TEXCOORD0.xyxy;
					    u_xlat18 = u_xlat5.y * 5.0;
					    u_xlat18 = sin(u_xlat18);
					    u_xlat1.x = sin(u_xlat4.w);
					    u_xlat7 = u_xlat2.x * u_xlat4.x;
					    u_xlat7 = u_xlat5.x * u_xlat7;
					    u_xlat7 = u_xlat7 * u_xlat18 + u_xlat1.x;
					    u_xlat12.x = u_xlat12.x * u_xlat18 + u_xlat1.x;
					    u_xlat12.x = sin(u_xlat12.x);
					    u_xlat6 = abs(u_xlat12.x) * u_xlat0.y;
					    u_xlat12.x = sin(u_xlat7);
					    u_xlat0.x = u_xlat12.x * u_xlat0.x;
					    u_xlat12.xy = vs_TEXCOORD0.xy + vec2(-0.5, 0.5);
					    u_xlat12.x = u_xlat12.x * u_xlat1.z;
					    u_xlat1.x = u_xlat1.z * u_xlat5.z;
					    u_xlat7 = sin(u_xlat5.w);
					    u_xlat1.x = u_xlat7 * u_xlat1.x;
					    u_xlat1.x = u_xlat1.x * 0.200000003;
					    u_xlat1.x = sin(u_xlat1.x);
					    u_xlat18 = sin(u_xlat12.y);
					    u_xlat12.x = u_xlat18 * u_xlat12.x;
					    u_xlat12.x = sin(u_xlat12.x);
					    u_xlat12.x = abs(u_xlat12.x) * u_xlat2.x;
					    u_xlat12.x = u_xlat12.x * 0.5;
					    u_xlat6 = u_xlat6 * 0.5 + u_xlat12.x;
					    u_xlat0.x = u_xlat0.x * 0.5 + u_xlat12.x;
					    u_xlat12.x = abs(u_xlat1.x) * u_xlat3.x;
					    u_xlat18 = u_xlat1.x * u_xlat3.x;
					    u_xlat1.y = u_xlat18 * 0.100000001 + u_xlat0.x;
					    u_xlat1.z = u_xlat12.x * 0.100000001 + u_xlat6;
					    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
					    u_xlat1.x = float(0.0);
					    u_xlat1.w = float(1.0);
					    SV_Target0 = u_xlat0 + u_xlat1;
					    return;
					}"
				}
			}
		}
	}
}