namespace uTools
{
	public enum EaseType
	{
		none = 0,
		easeInQuad = 1,
		easeOutQuad = 2,
		easeInOutQuad = 3,
		easeInCubic = 4,
		easeOutCubic = 5,
		easeInOutCubic = 6,
		easeInQuart = 7,
		easeOutQuart = 8,
		easeInOutQuart = 9,
		easeInQuint = 10,
		easeOutQuint = 11,
		easeInOutQuint = 12,
		easeInSine = 13,
		easeOutSine = 14,
		easeInOutSine = 15,
		easeInExpo = 16,
		easeOutExpo = 17,
		easeInOutExpo = 18,
		easeInCirc = 19,
		easeOutCirc = 20,
		easeInOutCirc = 21,
		linear = 22,
		spring = 23,
		easeInBounce = 24,
		easeOutBounce = 25,
		easeInOutBounce = 26,
		easeInBack = 27,
		easeOutBack = 28,
		easeInOutBack = 29,
		easeInElastic = 30,
		easeOutElastic = 31,
		easeInOutElastic = 32,
		punch = 33,
	}
}
